### ISSUE TITLE
Add Xcodeproj for easy Clone & Go

### ISSUE THREAD

**Issue by jonnyklemmer** [0xLeif/SwiftUIKit#145]
Currently repo requires running `swift package generate-xcodeproj` before a user can open repository in xcode. Checkin the results of that output

**Comment by 0xLeif** [comment]
![CleanShot 2020-05-12 at 20 47 19](https://user-images.githubusercontent.com/8268288/81762250-cd138a00-9491-11ea-97cb-52670702fc64.png)

Make sure to specify that it is for iOS!

**Comment by Oschly** [comment]
I would leave it as it is. .xcodeproj contains personal data, that sometimes can be commited to the repo, it's just safer to keep project without any files that we can generate.

**Comment by 0xLeif** [comment]
Closing issue.
