### ISSUE TITLE
TableView should default to true for shouldHighlightRowAtIndexPath

### ISSUE THREAD

**Issue by 0xLeif** [0xLeif/SwiftUIKit#153]
Expected
```swift
public func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
    shouldHighlightRowAtIndexPath?(indexPath) ?? true
}
```

Actual
```swift
public func tableView(_ tableView: UITableView, shouldHighlightRowAt indexPath: IndexPath) -> Bool {
    shouldHighlightRowAtIndexPath?(indexPath) ?? false
}
```

Reason 

To allow usage of `didSelectRowAtIndex` by default.
```swift
public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    didSelectRowAtIndexPath?(indexPath)
}
```

**Comment by ciccioska** [comment]
Hi, can you explain to me what do you mean with this issue? Thanks

**Comment by 0xLeif** [comment]
Hello @ciccioska 

When using `TableView`, if you want to use `didSelectRowAtIndexPath`, you must set `shouldHighlightRowAtIndexPath` to true for the row you want to be able to select.

```swift
table.register(cells: [PostCell.self])
                        .shouldHighlightRowAtIndexPath { _ in true }
                        .didSelectRowAtIndexPath { print($0) }
```

If you don't set this to true and leave it the default value of false, then you will not be able to select any tableView row. using `didSelectRowAtIndexPath`

**Comment by 0xLeif** [comment]
Thanks @ciccioska!
