### ISSUE TITLE
Using @_functionBuilder

### ISSUE THREAD

**Issue by muizidn** [0xLeif/SwiftUIKit#89]
Hi, this is great project. I am interested to see how people implement the open source version of Apple API.
A glimpse about your work, I see that it would be great if SwiftUIKit can use @_functionBuilder so the API can be designed to move closer to SwiftUI's one.

And would you like to have a look on my implementation? https://github.com/muizidn/FastUI, I am still working on it. Feel free to make issues 🙂

**Comment by zmeriksen** [comment]
Awesome suggestion! I will focus on implementing @_functionBuilder. I greatly appreciate you making an issue to let me know!

**Comment by 0xLeif** [comment]
Will not be implementing this due to the fact that @_functionBuilder is private and requires Swift 5.1
